import { jsPDF } from "jspdf";

interface FormResponse {
  question: string;
  answer: string | string[];
}

export const generateFormPDF = (
  formTitle: string,
  responses: FormResponse[],
  submissionDate: Date,
  isRTL: boolean = true
): void => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Set font that supports Hebrew if RTL
  doc.setFont("helvetica", "normal");
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = margin;

  // Helper function to add text with word wrap
  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number = 7): number => {
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string, index: number) => {
      if (y + index * lineHeight > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, x, y + index * lineHeight);
    });
    return y + lines.length * lineHeight;
  };

  // Title
  doc.setFontSize(20);
  doc.setTextColor(60, 60, 60);
  const titleX = isRTL ? pageWidth - margin : margin;
  doc.text(formTitle, titleX, yPosition, { align: isRTL ? "right" : "left" });
  yPosition += 15;

  // Submission date
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  const dateStr = submissionDate.toLocaleDateString(isRTL ? "he-IL" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(dateStr, titleX, yPosition, { align: isRTL ? "right" : "left" });
  yPosition += 15;

  // Separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Responses
  responses.forEach((response, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 50) {
      doc.addPage();
      yPosition = margin;
    }

    // Question number and text
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    const questionText = `${index + 1}. ${response.question}`;
    yPosition = addWrappedText(questionText, margin, yPosition, contentWidth);
    yPosition += 3;

    // Answer
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    const answerText = Array.isArray(response.answer) 
      ? response.answer.join(", ") 
      : response.answer || "-";
    yPosition = addWrappedText(answerText, margin + 5, yPosition, contentWidth - 10);
    yPosition += 10;
  });

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const footerText = isRTL ? "נוצר באמצעות Mind Hacker" : "Generated by Mind Hacker";
  doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: "center" });

  // Download the PDF
  const fileName = `${formTitle.replace(/[^a-zA-Z0-9\u0590-\u05FF]/g, "-")}-${submissionDate.getTime()}.pdf`;
  doc.save(fileName);
};
