import { jsPDF } from "jspdf";
import { loadHebrewFont } from "./fonts/hebrewFont";

interface FormResponse {
  question: string;
  answer: string | string[];
}

// Design tokens matching the website
const COLORS = {
  background: { r: 1, g: 10, b: 20 },      // #010a14
  backgroundLight: { r: 10, g: 25, b: 40 }, // Slightly lighter for cards
  primary: { r: 0, g: 229, b: 255 },        // #00e5ff (cyan)
  accent: { r: 245, g: 215, b: 135 },       // #f5d787 (gold)
  textLight: { r: 255, g: 255, b: 255 },    // White
  textMuted: { r: 150, g: 160, b: 170 },    // Muted gray
  separator: { r: 40, g: 60, b: 80 },       // Dark separator
};

// Helper to check if character is Hebrew
const isHebrew = (char: string): boolean => {
  const code = char.charCodeAt(0);
  return code >= 0x0590 && code <= 0x05FF;
};

// Reverse Hebrew text for proper RTL display in PDF
const reverseForRTL = (text: string): string => {
  // Split into segments of Hebrew and non-Hebrew
  const segments: { text: string; isHebrew: boolean }[] = [];
  let currentSegment = "";
  let currentIsHebrew = false;

  for (const char of text) {
    const charIsHebrew = isHebrew(char);
    if (currentSegment === "") {
      currentIsHebrew = charIsHebrew;
      currentSegment = char;
    } else if (charIsHebrew === currentIsHebrew) {
      currentSegment += char;
    } else {
      segments.push({ text: currentSegment, isHebrew: currentIsHebrew });
      currentSegment = char;
      currentIsHebrew = charIsHebrew;
    }
  }
  if (currentSegment) {
    segments.push({ text: currentSegment, isHebrew: currentIsHebrew });
  }

  // Reverse Hebrew segments and the order of all segments
  return segments
    .reverse()
    .map(seg => seg.isHebrew ? seg.text.split("").reverse().join("") : seg.text)
    .join("");
};

export interface BrandSettings {
  brandName: string;
  brandNameEn: string;
  primaryColor?: string;
}

export const generateFormPDF = async (
  formTitle: string,
  responses: FormResponse[],
  submissionDate: Date,
  isRTL: boolean = true,
  brandSettings?: BrandSettings
): Promise<void> => {
  // Use brand settings or fallback to defaults
  const brandName = brandSettings?.brandName || "MIND HACKER";
  const brandNameEn = brandSettings?.brandNameEn || "Mind Hacker";
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Load and register Hebrew font if RTL
  if (isRTL) {
    const hebrewFontBase64 = await loadHebrewFont();
    if (hebrewFontBase64) {
      doc.addFileToVFS("NotoSansHebrew-Regular.ttf", hebrewFontBase64);
      doc.addFont("NotoSansHebrew-Regular.ttf", "NotoSansHebrew", "normal");
      doc.setFont("NotoSansHebrew", "normal");
    } else {
      doc.setFont("helvetica", "normal");
    }
  } else {
    doc.setFont("helvetica", "normal");
  }

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Helper to draw background on current page
  const drawPageBackground = () => {
    // Dark gradient background
    doc.setFillColor(COLORS.background.r, COLORS.background.g, COLORS.background.b);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
    
    // Subtle gradient overlay at top
    for (let i = 0; i < 30; i++) {
      const alpha = 1 - (i / 30);
      doc.setFillColor(
        COLORS.background.r + (COLORS.backgroundLight.r - COLORS.background.r) * alpha * 0.3,
        COLORS.background.g + (COLORS.backgroundLight.g - COLORS.background.g) * alpha * 0.3,
        COLORS.background.b + (COLORS.backgroundLight.b - COLORS.background.b) * alpha * 0.3
      );
      doc.rect(0, i * 2, pageWidth, 2, "F");
    }
  };

  // Helper to draw header with logo
  const drawHeader = () => {
    // Cyan accent bar at top
    doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.rect(0, 0, pageWidth, 3, "F");
    
    // Branding text as logo - use dynamic brand name
    doc.setFontSize(10);
    doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    const brandText = brandNameEn.toUpperCase();
    doc.text(brandText, pageWidth / 2, 12, { align: "center" });
    
    // Decorative line under brand
    doc.setDrawColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.setLineWidth(0.3);
    const brandWidth = doc.getTextWidth(brandText);
    doc.line(pageWidth / 2 - brandWidth / 2 - 10, 14, pageWidth / 2 + brandWidth / 2 + 10, 14);
  };

  // Helper to draw footer
  const drawFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(COLORS.textMuted.r, COLORS.textMuted.g, COLORS.textMuted.b);
    const footerText = isRTL ? reverseForRTL(`נוצר באמצעות ${brandName}`) : `Generated by ${brandNameEn}`;
    doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: "center" });
    
    // Bottom accent line
    doc.setDrawColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
  };

  // Helper to add wrapped text with RTL support
  const addWrappedText = (
    text: string,
    x: number,
    y: number,
    maxWidth: number,
    lineHeight: number = 6,
    color: { r: number; g: number; b: number } = COLORS.textLight
  ): number => {
    doc.setTextColor(color.r, color.g, color.b);
    const processedText = isRTL ? reverseForRTL(text) : text;
    const lines = doc.splitTextToSize(processedText, maxWidth);
    
    let currentY = y;
    lines.forEach((line: string) => {
      if (currentY > pageHeight - 30) {
        doc.addPage();
        drawPageBackground();
        drawHeader();
        drawFooter();
        currentY = 35;
      }
      const textX = isRTL ? pageWidth - margin : x;
      doc.text(line, textX, currentY, { align: isRTL ? "right" : "left" });
      currentY += lineHeight;
    });
    
    return currentY;
  };

  // Draw question box
  const drawQuestionBox = (
    questionNum: number,
    question: string,
    answer: string,
    yPos: number
  ): number => {
    const boxPadding = 8;
    const questionLines = doc.splitTextToSize(isRTL ? reverseForRTL(question) : question, contentWidth - 25);
    const answerLines = doc.splitTextToSize(isRTL ? reverseForRTL(answer) : answer, contentWidth - 15);
    const boxHeight = (questionLines.length * 6) + (answerLines.length * 6) + boxPadding * 3 + 5;

    // Check if we need a new page
    if (yPos + boxHeight > pageHeight - 30) {
      doc.addPage();
      drawPageBackground();
      drawHeader();
      drawFooter();
      yPos = 35;
    }

    // Glass-effect box background
    doc.setFillColor(COLORS.backgroundLight.r, COLORS.backgroundLight.g, COLORS.backgroundLight.b);
    doc.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, "F");
    
    // Left/Right accent border
    doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    if (isRTL) {
      doc.roundedRect(pageWidth - margin - 3, yPos, 3, boxHeight, 0, 0, "F");
    } else {
      doc.roundedRect(margin, yPos, 3, boxHeight, 0, 0, "F");
    }

    let innerY = yPos + boxPadding;

    // Question number circle
    const circleX = isRTL ? pageWidth - margin - 12 : margin + 12;
    doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.circle(circleX, innerY + 2, 4, "F");
    doc.setFontSize(9);
    doc.setTextColor(COLORS.background.r, COLORS.background.g, COLORS.background.b);
    doc.text(String(questionNum), circleX, innerY + 3, { align: "center" });

    // Question text
    doc.setFontSize(11);
    doc.setTextColor(COLORS.textLight.r, COLORS.textLight.g, COLORS.textLight.b);
    const questionX = isRTL ? pageWidth - margin - boxPadding : margin + boxPadding + 15;
    questionLines.forEach((line: string, idx: number) => {
      doc.text(line, questionX, innerY + 2 + (idx * 6), { align: isRTL ? "right" : "left" });
    });
    innerY += questionLines.length * 6 + 8;

    // Separator line
    doc.setDrawColor(COLORS.separator.r, COLORS.separator.g, COLORS.separator.b);
    doc.setLineWidth(0.3);
    doc.line(margin + boxPadding, innerY - 3, pageWidth - margin - boxPadding, innerY - 3);

    // Answer text
    doc.setFontSize(10);
    doc.setTextColor(COLORS.accent.r, COLORS.accent.g, COLORS.accent.b);
    const answerX = isRTL ? pageWidth - margin - boxPadding : margin + boxPadding;
    answerLines.forEach((line: string, idx: number) => {
      doc.text(line, answerX, innerY + (idx * 6), { align: isRTL ? "right" : "left" });
    });

    return yPos + boxHeight + 8;
  };

  // === START BUILDING THE PDF ===
  
  // First page setup
  drawPageBackground();
  drawHeader();
  drawFooter();

  let yPosition = 25;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
  const titleText = isRTL ? reverseForRTL(formTitle) : formTitle;
  doc.text(titleText, pageWidth / 2, yPosition, { align: "center" });
  yPosition += 12;

  // Submission date
  doc.setFontSize(10);
  doc.setTextColor(COLORS.textMuted.r, COLORS.textMuted.g, COLORS.textMuted.b);
  const dateStr = submissionDate.toLocaleDateString(isRTL ? "he-IL" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  const dateText = isRTL ? reverseForRTL(dateStr) : dateStr;
  doc.text(dateText, pageWidth / 2, yPosition, { align: "center" });
  yPosition += 12;

  // Decorative separator
  doc.setDrawColor(COLORS.separator.r, COLORS.separator.g, COLORS.separator.b);
  doc.setLineWidth(0.5);
  doc.line(margin + 20, yPosition, pageWidth - margin - 20, yPosition);
  
  // Cyan dot in center
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
  doc.circle(pageWidth / 2, yPosition, 2, "F");
  yPosition += 15;

  // Responses
  responses.forEach((response, index) => {
    const answerText = Array.isArray(response.answer)
      ? response.answer.join(", ")
      : response.answer || "-";
    
    yPosition = drawQuestionBox(index + 1, response.question, answerText, yPosition);
  });

  // Download the PDF
  const fileName = `${formTitle.replace(/[^a-zA-Z0-9\u0590-\u05FF]/g, "-")}-${submissionDate.getTime()}.pdf`;
  doc.save(fileName);
};
