/**
 * Vitality Intake FlowSpec — Standalone intake form
 * All questions map directly to the vitality data map keys.
 * Saved to life_domains.domain_config for domain_id='vitality' under 'intake_answers'.
 */
import type { FlowSpec } from '@/lib/flow/types';

const DB = { table: 'life_domains', column: 'domain_config', jsonPath: 'intake_answers' };

export const vitalityIntakeSpec: FlowSpec = {
  id: 'vitality-intake',
  title_he: 'סריקת חיוניות',
  title_en: 'Vitality Scan',
  steps: [
    // ── Step 1: Sleep ──
    {
      id: 1,
      title_he: 'שינה',
      title_en: 'Sleep',
      renderer: 'card',
      miniSteps: [
        {
          id: 'sleep_duration_avg',
          title_he: 'כמה שעות שינה אתה ישן בממוצע?',
          title_en: 'How many hours of sleep do you get on average?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'under_5', label_he: 'פחות מ-5', label_en: 'Under 5h', icon: '🔴' },
            { value: '5_6', label_he: '5-6 שעות', label_en: '5-6h', icon: '🟠' },
            { value: '6_7', label_he: '6-7 שעות', label_en: '6-7h', icon: '🟡' },
            { value: '7_8', label_he: '7-8 שעות', label_en: '7-8h', icon: '🟢' },
            { value: '8_plus', label_he: '8+ שעות', label_en: '8+ hours', icon: '💤' },
          ],
        },
        {
          id: 'sleep_quality',
          title_he: 'איכות השינה שלך (1 = גרועה, 5 = מעולה)',
          title_en: 'Your sleep quality (1 = poor, 5 = excellent)',
          inputType: 'slider',
          sliderMin: 1,
          sliderMax: 5,
          sliderStep: 1,
          validation: { required: true },
          dbPath: DB,
        },
        {
          id: 'sleep_latency',
          title_he: 'כמה זמן לוקח לך להירדם?',
          title_en: 'How long does it take you to fall asleep?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: '0_10', label_he: '0-10 דקות', label_en: '0-10 min', icon: '😴' },
            { value: '10_20', label_he: '10-20 דקות', label_en: '10-20 min', icon: '🟢' },
            { value: '20_40', label_he: '20-40 דקות', label_en: '20-40 min', icon: '🟡' },
            { value: '40_plus', label_he: '40+ דקות', label_en: '40+ min', icon: '🔴' },
          ],
        },
        {
          id: 'wake_during_night',
          title_he: 'כמה פעמים אתה מתעורר בלילה?',
          title_en: 'How often do you wake up during the night?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'never', label_he: 'לעולם לא', label_en: 'Never', icon: '😴' },
            { value: '1x', label_he: 'פעם אחת', label_en: 'Once', icon: '🌙' },
            { value: '2x_plus', label_he: '2+ פעמים', label_en: '2+ times', icon: '😐' },
            { value: 'often', label_he: 'לעתים קרובות', label_en: 'Often', icon: '😫' },
          ],
        },
        {
          id: 'snoring',
          title_he: 'האם אתה נוחר?',
          title_en: 'Do you snore?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'no', label_he: 'לא', label_en: 'No', icon: '😴' },
            { value: 'sometimes', label_he: 'לפעמים', label_en: 'Sometimes', icon: '😐' },
            { value: 'yes', label_he: 'כן', label_en: 'Yes', icon: '😤' },
          ],
        },
        {
          id: 'sleep_apnea_suspect',
          title_he: 'האם אתה מתעורר נחנק/ת או עם תחושת חנק?',
          title_en: 'Do you wake up choking or gasping?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'no', label_he: 'לא', label_en: 'No', icon: '✅' },
            { value: 'yes', label_he: 'כן', label_en: 'Yes', icon: '⚠️' },
          ],
        },
        {
          id: 'sleep_schedule_consistency',
          title_he: 'כמה ימים בשבוע אתה הולך לישון/קם באותה שעה?',
          title_en: 'How many days/week do you keep consistent sleep/wake times?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: '0_2', label_he: '0-2 ימים', label_en: '0-2 days', icon: '🔴' },
            { value: '3_4', label_he: '3-4 ימים', label_en: '3-4 days', icon: '🟡' },
            { value: '5_7', label_he: '5-7 ימים', label_en: '5-7 days', icon: '🟢' },
          ],
        },
        {
          id: 'screen_before_bed',
          title_he: 'האם אתה משתמש במסכים לפני השינה?',
          title_en: 'Do you use screens before bed?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'no', label_he: 'לא', label_en: 'No', icon: '🚫' },
            { value: 'sometimes', label_he: 'לפעמים', label_en: 'Sometimes', icon: '📱' },
            { value: 'yes', label_he: 'כן, תמיד', label_en: 'Yes, always', icon: '💡' },
          ],
        },
      ],
    },

    // ── Step 2: Circadian ──
    {
      id: 2,
      title_he: 'מקצב יממתי',
      title_en: 'Circadian Rhythm',
      renderer: 'card',
      miniSteps: [
        {
          id: 'wake_time',
          title_he: 'באיזו שעה אתה קם בדרך כלל?',
          title_en: 'What time do you usually wake up?',
          inputType: 'time_picker',
          validation: { required: true },
          dbPath: DB,
        },
        {
          id: 'sleep_time',
          title_he: 'באיזו שעה אתה הולך לישון?',
          title_en: 'What time do you go to sleep?',
          inputType: 'time_picker',
          validation: { required: true },
          dbPath: DB,
        },
        {
          id: 'desired_wake_time',
          title_he: 'באיזו שעה היית רוצה לקום?',
          title_en: 'What time would you like to wake up?',
          inputType: 'time_picker',
          validation: { required: false },
          dbPath: DB,
        },
        {
          id: 'sunlight_after_waking',
          title_he: 'האם אתה מקבל אור שמש תוך 30 דקות מהקימה?',
          title_en: 'Do you get sunlight within 30 min of waking?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'yes', label_he: 'כן', label_en: 'Yes', icon: '☀️' },
            { value: 'sometimes', label_he: 'לפעמים', label_en: 'Sometimes', icon: '🌤️' },
            { value: 'no', label_he: 'לא', label_en: 'No', icon: '🌑' },
          ],
        },
        {
          id: 'energy_peak_time',
          title_he: 'מתי האנרגיה שלך בשיא?',
          title_en: 'When is your energy at its peak?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'early_morning', label_he: 'בוקר מוקדם', label_en: 'Early morning', icon: '🌅' },
            { value: 'mid_morning', label_he: 'אמצע הבוקר', label_en: 'Mid-morning', icon: '☀️' },
            { value: 'afternoon', label_he: 'אחה"צ', label_en: 'Afternoon', icon: '🌤️' },
            { value: 'evening', label_he: 'ערב', label_en: 'Evening', icon: '🌙' },
          ],
        },
        {
          id: 'energy_crash_time',
          title_he: 'מתי אתה חווה ירידה באנרגיה?',
          title_en: 'When do you experience energy crashes?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'no_crash', label_he: 'אין ירידות', label_en: 'No crashes', icon: '✅' },
            { value: 'morning', label_he: 'בוקר', label_en: 'Morning', icon: '😴' },
            { value: 'after_lunch', label_he: 'אחרי הצהריים', label_en: 'After lunch', icon: '🥱' },
            { value: 'late_afternoon', label_he: 'אחה"צ מאוחר', label_en: 'Late afternoon', icon: '😪' },
            { value: 'evening', label_he: 'ערב', label_en: 'Evening', icon: '🌙' },
          ],
        },
        {
          id: 'failure_moment',
          title_he: 'מתי הכי קשה לך להתחיל את היום?',
          title_en: 'When is your hardest failure window?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'morning_start', label_he: 'תחילת הבוקר', label_en: 'Morning start', icon: '🌅' },
            { value: 'after_lunch', label_he: 'אחרי ארוחת צהריים', label_en: 'After lunch', icon: '🥱' },
            { value: 'late_afternoon', label_he: 'אחה"צ מאוחר', label_en: 'Late afternoon', icon: '😪' },
            { value: 'evening', label_he: 'ערב', label_en: 'Evening', icon: '🌙' },
            { value: 'no_pattern', label_he: 'אין דפוס ברור', label_en: 'No clear pattern', icon: '🤷' },
          ],
        },
      ],
    },

    // ── Step 3: Energy & Mood ──
    {
      id: 3,
      title_he: 'אנרגיה ומצב רוח',
      title_en: 'Energy & Mood',
      renderer: 'card',
      miniSteps: [
        {
          id: 'avg_energy_level',
          title_he: 'דירוג אנרגיה יומי ממוצע (1 = נמוך מאוד, 10 = מלא אנרגיה)',
          title_en: 'Average daily energy level (1 = very low, 10 = full energy)',
          inputType: 'slider',
          sliderMin: 1,
          sliderMax: 10,
          sliderStep: 1,
          validation: { required: true },
          dbPath: DB,
        },
        {
          id: 'energy_volatility',
          title_he: 'האם האנרגיה שלך יציבה או תנודתית במהלך היום?',
          title_en: 'Is your energy stable or volatile throughout the day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'stable', label_he: 'יציבה', label_en: 'Stable', icon: '📊' },
            { value: 'moderate', label_he: 'תנודות קלות', label_en: 'Moderate swings', icon: '📈' },
            { value: 'volatile', label_he: 'תנודתית מאוד', label_en: 'Very volatile', icon: '🎢' },
          ],
        },
        {
          id: 'baseline_mood',
          title_he: 'מהו מצב הרוח הבסיסי שלך ביום ממוצע?',
          title_en: 'What is your baseline mood on an average day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'calm', label_he: 'רגוע', label_en: 'Calm', icon: '😌' },
            { value: 'neutral', label_he: 'נייטרלי', label_en: 'Neutral', icon: '😐' },
            { value: 'tense', label_he: 'דרוך / מתוח', label_en: 'Tense / On-edge', icon: '😬' },
            { value: 'low', label_he: 'מדוכדך / עצוב', label_en: 'Low / Sad', icon: '😔' },
          ],
        },
        {
          id: 'anxiety_level',
          title_he: 'רמת חרדה כללית (0 = אין, 10 = גבוהה מאוד)',
          title_en: 'General anxiety level (0 = none, 10 = very high)',
          inputType: 'slider',
          sliderMin: 0,
          sliderMax: 10,
          sliderStep: 1,
          validation: { required: true },
          dbPath: DB,
        },
      ],
    },

    // ── Step 4: Stress & Recovery ──
    {
      id: 4,
      title_he: 'סטרס והתאוששות',
      title_en: 'Stress & Recovery',
      renderer: 'card',
      miniSteps: [
        {
          id: 'current_stress',
          title_he: 'רמת הסטרס הנוכחית שלך (1 = נמוכה, 10 = גבוהה מאוד)',
          title_en: 'Your current stress level (1 = low, 10 = very high)',
          inputType: 'slider',
          sliderMin: 1,
          sliderMax: 10,
          sliderStep: 1,
          validation: { required: true },
          dbPath: DB,
        },
        {
          id: 'relaxation_frequency',
          title_he: 'כמה פעמים בשבוע אתה עושה משהו מרגיע באמת? (נשימות, מדיטציה, הליכה, סאונה)',
          title_en: 'How many times/week do you do something truly relaxing? (breathwork, meditation, walking, sauna)',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'never', label_he: 'כמעט אף פעם', label_en: 'Almost never', icon: '🔴' },
            { value: '1_2', label_he: '1-2 פעמים', label_en: '1-2 times', icon: '🟡' },
            { value: '3_5', label_he: '3-5 פעמים', label_en: '3-5 times', icon: '🟢' },
            { value: 'daily', label_he: 'כל יום', label_en: 'Daily', icon: '🧘' },
          ],
        },
        {
          id: 'has_hrv_device',
          title_he: 'יש לך שעון חכם / מכשיר שמודד דופק מנוחה או HRV?',
          title_en: 'Do you have a smartwatch / device that measures resting HR or HRV?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'yes', label_he: 'כן', label_en: 'Yes', icon: '⌚' },
            { value: 'no', label_he: 'לא', label_en: 'No', icon: '🚫' },
          ],
        },
      ],
    },

    // ── Step 5: Dopamine Load ──
    {
      id: 5,
      title_he: 'עומס דופמין',
      title_en: 'Dopamine Load',
      renderer: 'card',
      miniSteps: [
        {
          id: 'daily_screen_time',
          title_he: 'כמה שעות מסך שלא לעבודה ביום?',
          title_en: 'How many hours of non-work screen time per day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'under_30m', label_he: 'פחות מ-30 דקות', label_en: 'Under 30 min', icon: '✅' },
            { value: '30_60m', label_he: '30-60 דקות', label_en: '30-60 min', icon: '📱' },
            { value: '1_2h', label_he: '1-2 שעות', label_en: '1-2 hours', icon: '📲' },
            { value: '2_4h', label_he: '2-4 שעות', label_en: '2-4 hours', icon: '🔴' },
            { value: '4h_plus', label_he: '4+ שעות', label_en: '4+ hours', icon: '🚨' },
          ],
        },
        {
          id: 'shorts_reels',
          title_he: 'באיזו תדירות אתה צופה בסרטונים קצרים (Reels/Shorts)?',
          title_en: 'How often do you watch short-form content (Reels/Shorts)?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'never', label_he: 'אף פעם', label_en: 'Never', icon: '🚫' },
            { value: 'sometimes', label_he: 'לפעמים', label_en: 'Sometimes', icon: '📱' },
            { value: 'daily', label_he: 'יומי', label_en: 'Daily', icon: '📲' },
            { value: 'heavy_daily', label_he: 'הרבה כל יום', label_en: 'Heavy daily', icon: '🔴' },
          ],
        },
        {
          id: 'gaming',
          title_he: 'באיזו תדירות אתה משחק במשחקי וידאו?',
          title_en: 'How often do you play video games?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'none', label_he: 'בכלל לא', label_en: 'None', icon: '🚫' },
            { value: 'weekends', label_he: 'סופ"ש בלבד', label_en: 'Weekends only', icon: '🎮' },
            { value: 'few_days', label_he: 'כמה פעמים בשבוע', label_en: 'Few days a week', icon: '🕹️' },
            { value: 'daily', label_he: 'כל יום', label_en: 'Daily', icon: '🔴' },
          ],
        },
        {
          id: 'porn_frequency',
          title_he: 'תדירות צפייה בפורנוגרפיה',
          title_en: 'Pornography viewing frequency',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'never', label_he: 'אף פעם', label_en: 'Never', icon: '🚫' },
            { value: 'prefer_not', label_he: 'מעדיף לא לענות', label_en: 'Prefer not to say', icon: '🤐' },
            { value: 'monthly', label_he: 'חודשית', label_en: 'Monthly', icon: '📅' },
            { value: 'weekly', label_he: 'שבועית', label_en: 'Weekly', icon: '📆' },
            { value: '2_5x_week', label_he: '2-5 פעמים בשבוע', label_en: '2-5x/week', icon: '🔴' },
            { value: 'daily', label_he: 'יומית', label_en: 'Daily', icon: '🚨' },
          ],
        },
        {
          id: 'late_night_scrolling',
          title_he: 'גלילה במיטה לפני שינה',
          title_en: 'In-bed scrolling before sleep',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'never', label_he: 'אף פעם', label_en: 'Never', icon: '🚫' },
            { value: 'sometimes', label_he: 'לפעמים', label_en: 'Sometimes', icon: '📱' },
            { value: 'often', label_he: 'כמעט כל לילה', label_en: 'Almost every night', icon: '🔴' },
          ],
        },
      ],
    },

    // ── Step 6: Nutrition & Hydration ──
    {
      id: 6,
      title_he: 'תזונה ונוזלים',
      title_en: 'Nutrition & Hydration',
      renderer: 'card',
      miniSteps: [
        {
          id: 'diet_type',
          title_he: 'איזה סגנון תזונה מתאר אותך?',
          title_en: 'What diet style describes you?',
          inputType: 'multi_select',
          validation: { required: true, minSelected: 1 },
          dbPath: DB,
          options: [
            { value: 'balanced', label_he: 'מאוזנת', label_en: 'Balanced', icon: '🥗' },
            { value: 'mediterranean', label_he: 'ים תיכונית', label_en: 'Mediterranean', icon: '🫒' },
            { value: 'paleo', label_he: 'פליאו', label_en: 'Paleo', icon: '🥩' },
            { value: 'carnivore', label_he: 'קרניבור', label_en: 'Carnivore', icon: '🥓' },
            { value: 'keto', label_he: 'קטו', label_en: 'Keto', icon: '🥑' },
            { value: 'alkaline', label_he: 'אלקליינית', label_en: 'Alkaline', icon: '🥬' },
            { value: 'vegan', label_he: 'טבעונית', label_en: 'Vegan', icon: '🌱' },
            { value: 'vegetarian', label_he: 'צמחונית', label_en: 'Vegetarian', icon: '🥦' },
            { value: 'raw_food', label_he: 'מזון חי', label_en: 'Raw Food', icon: '🥕' },
            { value: 'intermittent_fasting', label_he: 'צום לסירוגין', label_en: 'Intermittent Fasting', icon: '⏱️' },
            { value: 'whole30', label_he: 'Whole30', label_en: 'Whole30', icon: '🍽️' },
            { value: 'gluten_free', label_he: 'ללא גלוטן', label_en: 'Gluten Free', icon: '🌾' },
            { value: 'chaotic', label_he: 'כאוטית / ללא מבנה', label_en: 'Chaotic / No structure', icon: '🍕' },
          ],
        },
        {
          id: 'meals_per_day',
          title_he: 'כמה ארוחות אתה אוכל ביום?',
          title_en: 'How many meals do you eat per day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: '1', label_he: 'אחת', label_en: '1', icon: '1️⃣' },
            { value: '2', label_he: 'שתיים', label_en: '2', icon: '2️⃣' },
            { value: '3', label_he: 'שלוש', label_en: '3', icon: '3️⃣' },
            { value: '4_plus', label_he: '4+', label_en: '4+', icon: '4️⃣' },
          ],
        },
        {
          id: 'protein_estimate',
          title_he: 'הערכת צריכת חלבון יומית',
          title_en: 'Daily protein intake estimate',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'low', label_he: 'נמוכה (פחות מ-60 גרם)', label_en: 'Low (under 60g)', icon: '🔴' },
            { value: 'moderate', label_he: 'בינונית (60-120 גרם)', label_en: 'Moderate (60-120g)', icon: '🟡' },
            { value: 'high', label_he: 'גבוהה (120+ גרם)', label_en: 'High (120g+)', icon: '🟢' },
            { value: 'no_idea', label_he: 'לא יודע', label_en: 'No idea', icon: '❓' },
          ],
        },
        {
          id: 'fiber_veggie_intake',
          title_he: 'כמה מנות ירקות/סיבים ביום?',
          title_en: 'How many servings of vegetables/fiber per day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'almost_none', label_he: 'כמעט לא', label_en: 'Almost none', icon: '🔴' },
            { value: '1_2', label_he: '1-2 מנות', label_en: '1-2 servings', icon: '🟡' },
            { value: '3_5', label_he: '3-5 מנות', label_en: '3-5 servings', icon: '🟢' },
            { value: '5_plus', label_he: '5+ מנות', label_en: '5+ servings', icon: '💚' },
          ],
        },
        {
          id: 'late_eating_frequency',
          title_he: 'כמה פעמים בשבוע אתה אוכל אכילה מאוחרת? (אחרי 21:00)',
          title_en: 'How many times/week do you eat late? (after 9pm)',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: '0', label_he: 'אף פעם', label_en: 'Never', icon: '✅' },
            { value: '1_2', label_he: '1-2 פעמים', label_en: '1-2 times', icon: '🟡' },
            { value: '3_5', label_he: '3-5 פעמים', label_en: '3-5 times', icon: '🟠' },
            { value: 'daily', label_he: 'כל יום', label_en: 'Every day', icon: '🔴' },
          ],
        },
        {
          id: 'eating_window',
          title_he: 'כמה שעות ביום אתה אוכל? (חלון אכילה)',
          title_en: 'How many hours/day is your eating window?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: '4_6', label_he: '4-6 שעות', label_en: '4-6 hours', icon: '⏱️' },
            { value: '6_8', label_he: '6-8 שעות', label_en: '6-8 hours', icon: '🟢' },
            { value: '8_10', label_he: '8-10 שעות', label_en: '8-10 hours', icon: '🟡' },
            { value: '10_plus', label_he: '10+ שעות', label_en: '10+ hours', icon: '🔴' },
          ],
        },
        {
          id: 'protein_awareness',
          title_he: 'מודעות לצריכת חלבון',
          title_en: 'Protein intake awareness',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'track_it', label_he: 'עוקב ומודד', label_en: 'Track it', icon: '📊' },
            { value: 'some', label_he: 'מודע חלקית', label_en: 'Somewhat aware', icon: '🤔' },
            { value: 'no_idea', label_he: 'לא יודע', label_en: 'No idea', icon: '❓' },
          ],
        },
        {
          id: 'nutrition_weak_point',
          title_he: 'מה הנקודה החלשה שלך בתזונה?',
          title_en: 'What is your biggest nutrition weak point?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'sugar', label_he: 'סוכר', label_en: 'Sugar', icon: '🍬' },
            { value: 'late_night_eating', label_he: 'אכילת לילה', label_en: 'Late-night eating', icon: '🌙' },
            { value: 'skipping_meals', label_he: 'דילוג על ארוחות', label_en: 'Skipping meals', icon: '⏭️' },
            { value: 'ultra_processed', label_he: 'מזון מעובד', label_en: 'Ultra-processed food', icon: '🍟' },
            { value: 'inconsistent_timing', label_he: 'זמנים לא קבועים', label_en: 'Inconsistent timing', icon: '⏰' },
          ],
        },
        {
          id: 'daily_fluid_volume',
          title_he: 'כמה נוזלים אתה שותה ביום?',
          title_en: 'How much total fluids per day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'under_1L', label_he: 'פחות מליטר', label_en: 'Under 1L', icon: '🔴' },
            { value: '1_2L', label_he: '1-2 ליטר', label_en: '1-2L', icon: '🟡' },
            { value: '2_3L', label_he: '2-3 ליטר', label_en: '2-3L', icon: '🟢' },
            { value: 'over_3L', label_he: '3+ ליטר', label_en: '3L+', icon: '💧' },
          ],
        },
        {
          id: 'fluid_sources',
          title_he: 'מקורות נוזלים עיקריים',
          title_en: 'Main fluid sources',
          inputType: 'multi_select',
          validation: { required: true, minSelected: 1 },
          dbPath: DB,
          options: [
            { value: 'water', label_he: 'מים', label_en: 'Water', icon: '💧' },
            { value: 'coffee', label_he: 'קפה', label_en: 'Coffee', icon: '☕' },
            { value: 'herbal_tea', label_he: 'תה צמחים', label_en: 'Herbal tea', icon: '🍵' },
            { value: 'coconut_water', label_he: 'מי קוקוס', label_en: 'Coconut water', icon: '🥥' },
            { value: 'natural_fruits', label_he: 'פירות טבעיים', label_en: 'Natural fruits', icon: '🍉' },
            { value: 'soft_drinks', label_he: 'שתייה ממותקת', label_en: 'Soft drinks', icon: '🥤' },
            { value: 'energy_drinks', label_he: 'משקאות אנרגיה', label_en: 'Energy drinks', icon: '⚡' },
          ],
        },
      ],
    },

    // ── Step 7: Substances & Caffeine ──
    {
      id: 7,
      title_he: 'חומרים וקפאין',
      title_en: 'Substances & Caffeine',
      renderer: 'card',
      miniSteps: [
        {
          id: 'caffeine_intake',
          title_he: 'כמה קפאין ביום?',
          title_en: 'How much caffeine per day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: '0', label_he: 'ללא', label_en: 'None', icon: '🚫' },
            { value: '1_cup', label_he: 'כוס אחת', label_en: '1 cup', icon: '☕' },
            { value: '2_3_cups', label_he: '2-3 כוסות', label_en: '2-3 cups', icon: '☕☕' },
            { value: '4_plus', label_he: '4+ כוסות', label_en: '4+ cups', icon: '🔴' },
          ],
        },
        {
          id: 'first_caffeine_timing',
          title_he: 'מתי הקפה הראשון?',
          title_en: 'When is your first caffeine?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'within_60min', label_he: 'תוך שעה מהקימה', label_en: 'Within 60 min of waking', icon: '⏰' },
            { value: '1_2h_after', label_he: '1-2 שעות אחרי', label_en: '1-2h after waking', icon: '🕐' },
            { value: '2h_plus', label_he: '2+ שעות אחרי', label_en: '2+ hours after', icon: '✅' },
          ],
        },
        {
          id: 'last_caffeine_time',
          title_he: 'מתי הקפאין האחרון שלך ביום?',
          title_en: 'When is your last caffeine of the day?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'before_12', label_he: 'לפני 12:00', label_en: 'Before 12pm', icon: '🟢' },
            { value: '12_14', label_he: '12:00-14:00', label_en: '12-2pm', icon: '🟡' },
            { value: '14_16', label_he: '14:00-16:00', label_en: '2-4pm', icon: '🟠' },
            { value: 'after_16', label_he: 'אחרי 16:00', label_en: 'After 4pm', icon: '🔴' },
          ],
        },
        {
          id: 'alcohol_frequency',
          title_he: 'תדירות שתיית אלכוהול',
          title_en: 'Alcohol frequency',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'never', label_he: 'לעולם לא', label_en: 'Never', icon: '🚫' },
            { value: '1x_week', label_he: 'פעם בשבוע', label_en: 'Once a week', icon: '🍷' },
            { value: '2_3x_week', label_he: '2-3 פעמים', label_en: '2-3x/week', icon: '🍺' },
            { value: '4x_plus', label_he: '4+ פעמים', label_en: '4+/week', icon: '🔴' },
          ],
        },
        {
          id: 'nicotine',
          title_he: 'שימוש בניקוטין',
          title_en: 'Nicotine use',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'none', label_he: 'ללא', label_en: 'None', icon: '🚫' },
            { value: 'sometimes', label_he: 'לפעמים', label_en: 'Sometimes', icon: '🚬' },
            { value: 'daily', label_he: 'יומי', label_en: 'Daily', icon: '🔴' },
          ],
        },
        {
          id: 'weed_thc',
          title_he: 'שימוש ב-THC / קנאביס',
          title_en: 'THC / Cannabis use',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'no', label_he: 'לא', label_en: 'No', icon: '🚫' },
            { value: 'sometimes', label_he: 'לפעמים', label_en: 'Sometimes', icon: '🌿' },
            { value: 'weekly', label_he: 'שבועי', label_en: 'Weekly', icon: '📆' },
            { value: 'daily', label_he: 'יומי', label_en: 'Daily', icon: '🔴' },
          ],
        },
      ],
    },

    // ── Step 8: Training, Movement & Recovery ──
    {
      id: 8,
      title_he: 'אימון, תנועה ושיקום',
      title_en: 'Training, Movement & Recovery',
      renderer: 'card',
      miniSteps: [
        {
          id: 'activity_level',
          title_he: 'כמה פעמים בשבוע אתה מתאמן?',
          title_en: 'How many times per week do you train?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'none', label_he: 'לא מתאמן', label_en: 'Not training', icon: '🚫' },
            { value: '1_2_week', label_he: '1-2 בשבוע', label_en: '1-2/week', icon: '🏃' },
            { value: '3_4_week', label_he: '3-4 בשבוע', label_en: '3-4/week', icon: '💪' },
            { value: '5_plus', label_he: '5+ בשבוע', label_en: '5+/week', icon: '🔥' },
            { value: 'athlete', label_he: 'ספורטאי מקצועי', label_en: 'Professional athlete', icon: '🏆' },
          ],
        },
        {
          id: 'training_window_available',
          title_he: 'מתי יש לך חלון לאימון?',
          title_en: 'When do you have a training window?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'morning', label_he: 'בוקר', label_en: 'Morning', icon: '🌅' },
            { value: 'midday', label_he: 'צהריים', label_en: 'Midday', icon: '☀️' },
            { value: 'evening', label_he: 'ערב', label_en: 'Evening', icon: '🌙' },
            { value: 'flexible', label_he: 'גמיש', label_en: 'Flexible', icon: '✅' },
            { value: 'none', label_he: 'אין חלון קבוע', label_en: 'No consistent window', icon: '❌' },
          ],
        },
        {
          id: 'daily_movement_neat',
          title_he: 'תנועה יומית שאינה אימון (הליכה, צעדים)',
          title_en: 'Daily non-exercise movement (walking, steps)',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'sedentary', label_he: 'יושב רוב היום', label_en: 'Sedentary most of the day', icon: '🪑' },
            { value: 'low', label_he: 'מעט תנועה (2,000-5,000 צעדים)', label_en: 'Low (2k-5k steps)', icon: '🟡' },
            { value: 'moderate', label_he: 'בינונית (5,000-8,000 צעדים)', label_en: 'Moderate (5k-8k steps)', icon: '🟢' },
            { value: 'high', label_he: 'גבוהה (8,000+ צעדים)', label_en: 'High (8k+ steps)', icon: '🚶' },
          ],
        },
        {
          id: 'active_work_hours',
          title_he: 'כמה שעות עבודה פעילה ביום?',
          title_en: 'How many active work hours per day?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: '0_2', label_he: '0-2', label_en: '0-2h', icon: '🟢' },
            { value: '2_4', label_he: '2-4', label_en: '2-4h', icon: '🟢' },
            { value: '4_6', label_he: '4-6', label_en: '4-6h', icon: '🟡' },
            { value: '6_8', label_he: '6-8', label_en: '6-8h', icon: '🟠' },
            { value: '8_10', label_he: '8-10', label_en: '8-10h', icon: '🔴' },
            { value: '10_plus', label_he: '10+', label_en: '10+h', icon: '🚨' },
          ],
        },
        {
          id: 'dependents',
          title_he: 'יש לך ילדים או תלויים?',
          title_en: 'Do you have children or dependents?',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'none', label_he: 'לא', label_en: 'No', icon: '🚫' },
            { value: '1_2', label_he: '1-2', label_en: '1-2', icon: '👶' },
            { value: '3_plus', label_he: '3+', label_en: '3+', icon: '👨‍👩‍👧‍👦' },
          ],
        },
        {
          id: 'availability_hours',
          title_he: 'כמה שעות אתה זמין / בכוננות ביום?',
          title_en: 'How many hours are you on-call / available per day?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: '0_4', label_he: '0-4 שעות', label_en: '0-4 hours', icon: '🟢' },
            { value: '4_8', label_he: '4-8 שעות', label_en: '4-8 hours', icon: '🟡' },
            { value: '8_12', label_he: '8-12 שעות', label_en: '8-12 hours', icon: '🟠' },
            { value: '12_plus', label_he: '12+ שעות', label_en: '12+ hours', icon: '🔴' },
          ],
        },
        {
          id: 'household_responsibility',
          title_he: 'רמת אחריות בבית',
          title_en: 'Household responsibility level',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'low', label_he: 'נמוכה', label_en: 'Low', icon: '🟢' },
            { value: 'medium', label_he: 'בינונית', label_en: 'Medium', icon: '🟡' },
            { value: 'high', label_he: 'גבוהה', label_en: 'High', icon: '🟠' },
            { value: 'very_high', label_he: 'גבוהה מאוד', label_en: 'Very high', icon: '🔴' },
          ],
        },
      ],
    },

    // ── Step 9: Body Baseline & Hormonal Signals ──
    {
      id: 9,
      title_he: 'פרופיל בסיסי ואותות הורמונליים',
      title_en: 'Body Baseline & Hormonal Signals',
      renderer: 'card',
      miniSteps: [
        {
          id: 'age_bracket',
          title_he: 'טווח גילאים',
          title_en: 'Age range',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: '16_18', label_he: '16-18', label_en: '16-18', icon: '🧒' },
            { value: '19_24', label_he: '19-24', label_en: '19-24', icon: '🧑' },
            { value: '25_34', label_he: '25-34', label_en: '25-34', icon: '👤' },
            { value: '35_44', label_he: '35-44', label_en: '35-44', icon: '👤' },
            { value: '45_54', label_he: '45-54', label_en: '45-54', icon: '👤' },
            { value: '55_plus', label_he: '55+', label_en: '55+', icon: '👤' },
          ],
        },
        {
          id: 'gender',
          title_he: 'מגדר',
          title_en: 'Gender',
          inputType: 'single_select',
          validation: { required: true },
          dbPath: DB,
          options: [
            { value: 'male', label_he: 'זכר', label_en: 'Male', icon: '♂️' },
            { value: 'female', label_he: 'נקבה', label_en: 'Female', icon: '♀️' },
            { value: 'other', label_he: 'אחר', label_en: 'Other', icon: '⚧️' },
          ],
        },
        {
          id: 'body_fat_estimate',
          title_he: 'הערכת אחוז שומן גוף',
          title_en: 'Body fat estimate',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          options: [
            { value: 'lean', label_he: 'רזה / שרירי', label_en: 'Lean', icon: '💪' },
            { value: 'average', label_he: 'ממוצע', label_en: 'Average', icon: '👤' },
            { value: 'high', label_he: 'גבוה', label_en: 'High', icon: '📈' },
            { value: 'very_high', label_he: 'גבוה מאוד', label_en: 'Very high', icon: '🔴' },
          ],
        },
        {
          id: 'libido_level',
          title_he: 'חשק מיני / ליבידו',
          title_en: 'Libido / Sex drive',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          branching: {
            showIf: (answers) => {
              const age = answers.age_bracket as string;
              return age !== '16_18';
            },
          },
          options: [
            { value: 'low', label_he: 'נמוך', label_en: 'Low', icon: '🔻' },
            { value: 'moderate', label_he: 'בינוני', label_en: 'Moderate', icon: '➖' },
            { value: 'high', label_he: 'גבוה', label_en: 'High', icon: '🔺' },
            { value: 'prefer_not', label_he: 'מעדיף/ה לא לומר', label_en: 'Prefer not to say', icon: '🤐' },
          ],
        },
        {
          id: 'menstrual_regularity',
          title_he: 'האם המחזור שלך סדיר?',
          title_en: 'Is your menstrual cycle regular?',
          inputType: 'single_select',
          validation: { required: false },
          dbPath: DB,
          branching: {
            showIf: (answers) => {
              const gender = answers.gender as string;
              const age = answers.age_bracket as string;
              return gender === 'female' && age !== '16_18';
            },
          },
          options: [
            { value: 'regular', label_he: 'כן, סדיר', label_en: 'Yes, regular', icon: '✅' },
            { value: 'irregular', label_he: 'לא, לא סדיר', label_en: 'No, irregular', icon: '⚠️' },
            { value: 'not_relevant', label_he: 'לא רלוונטי', label_en: 'Not relevant', icon: '➖' },
            { value: 'prefer_not', label_he: 'מעדיפה לא לומר', label_en: 'Prefer not to say', icon: '🤐' },
          ],
        },
      ],
    },
  ],
};
