// Primary homepage components - Mind OS architecture
export { default as GameHeroSection } from './GameHeroSection';
export { default as SystemArchitectureSection } from './SystemArchitectureSection';
export { default as LifePillarsSection } from './LifePillarsSection';
export { default as AuroraCoachSection } from './AuroraCoachSection';
export { default as HandsFreeSection } from './HandsFreeSection';
export { default as TransformationJourneySection } from './TransformationJourneySection';
export { default as WhyChooseUsSection } from './WhyChooseUsSection';
export { default as TransformationProofSection } from './TransformationProofSection';
export { default as FreeJourneyBannerSection } from './FreeJourneyBannerSection';
export { default as FearOfMissingOutSection } from './FearOfMissingOutSection';
export { default as FinalCTASection } from './FinalCTASection';
